### PR TITLE
Fix several memory leaks.

### PR DESCRIPTION
**Pull request by Quipyowert2**
Fixes a leak in ecl::LoadImage and another leak in SurfaceCache::acquire
where IMG_Load is called in an if statement.

### CODE REVIEW

**Comment by Quipyowert2** [comment]
Force pushed to fix double delete crash in Enigma by setting AdoptDocument parameter to true instead of commenting out `doc->release()` calls in destructors.

**Comment by Quipyowert2** [comment]
Added a `setFeature` call in `initXerces` to hopefully fix the double delete crash for Xerces 2.8 and earlier. I can't get that version of Xerces to compile.

**Comment by alochmann** [comment]
Hi,

thank you so much for those very valuable fixes! I reviewed your commits, and have three questions/annotations.

The first commit 5db5a17 effectively introduces a side effect ... a constructor which at the same time destructs something else. I am a bit uncomfortable with this unintuitive behaviour, and will expand on your commit, to make it more transparent.

The memory leak you address with commit 8dfae91 still worries me. You manually call ObjectValidator's shutdown ... however, this should have been called anyway by ObjectValidator's destructor. Your shutdown call doesn't hurt for sure, but it should not have fixed the memory leak ... that points at some greater problem.

I do not quite understand your commit e578a61. You redefine the =-operator to delete its left-side object, regardless of the argument on the right side? That would be very obfuscating, and pose a problem to further expansion of the code years in the future. I will probably rewrite your fix somehow ... unless, of course, I misunderstood your code?

Anyway, very good work, thank you again!

Cheers,
Andreas

**Comment by Quipyowert2** [comment]
The operator= and copy constructor in commit e578a61 doesn't delete any objects. `=delete` on the end of a function definition [prohibits copying](https://stackoverflow.com/a/5513928/8890345). I added `= delete` on the end of the copy constructor and copy assignment operator to prevent the operator from having a default implementation, since rule of three says the copy constructor and copy assignment operator should be defined if a custom destructor is used. If the Image needs to be copyable, the copy constructor and `operator=` should probably be implemented.

**Pull request merged**
